version: '3.8'

services:
  app:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --reload --access-logfile - --error-logfile - -m 007 'app:create_app()'
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443" # Add this line to handle HTTPS traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docs/build/html:/usr/share/nginx/html/docs:ro
      - ./app/static:/usr/share/nginx/html/static:ro
      - ./certbot:/etc/letsencrypt:ro # Mount the Certbot certificates
    depends_on:
      - app

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/etc:/etc/letsencrypt
  #     - ./certbot/var:/var/lib/letsencrypt
  #   entrypoint: '/bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"'
  #   depends_on:
  #     - nginx
