version: '3.8'

services:
  app:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 -m 007 'app:create_app()'
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/html:/usr/share/nginx/html/docs:ro
      - ./app/static:/usr/share/nginx/html/static:ro
    depends_on:
      - app
