version: '3.8'

services:
  app:
    restart: always
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --reload --access-logfile - --error-logfile - -m 007 'app:create_app()'
    volumes:
      - .:/usr/src/app:rw,Z
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443" # Add this line to handle HTTPS traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./docs/build/html:/usr/share/nginx/html/docs:ro,Z
      - ./app/static:/usr/share/nginx/html/static:ro,Z
      - ./certbot:/etc/letsencrypt:ro,Z
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./instance/postgres_data:/var/lib/postgresql/data
    env_file:
      - ".env"


  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/etc:/etc/letsencrypt
  #     - ./certbot/var:/var/lib/letsencrypt
  #   entrypoint: '/bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"'
  #   depends_on:
  #     - nginx
