"""Add Retirement model v1

Revision ID: b3b2812ceff6
Revises: 
Create Date: 2024-10-25 17:00:23.979913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b2812ceff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retirement_savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('accrual_rate', sa.Float(), nullable=False),
    sa.Column('accrual_hours_threshold', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacation')
    op.drop_table('retirement_savings')
    # ### end Alembic commands ###
